language: node_js
node_js:
- '0.11'
before_install:
- gem update --system
- gem install sass
- npm install -g grunt-cli
install: npm install
before_script: grunt dist
env:
  global:
  - secure: hp/5p+jHvTWEOkoKjiQf4EgAYq9g6IZ+KE5RLSf40KbOioCX+84XuRX05hBBINMXKcufluR1QrOMzBCzZU8I5UAMsvlCebYum40iuwAib5+SN+Y4t5M0QksBc+K6mWkzCMXBvbVPtYEEe3XmV/x4XstHSF8XszT5qdc9QJsLznQ=
  - secure: ZerTvVev7tZqPhZl5a0O9GXXUG301VuGvOrT7c8ObGEylWjFK3btEl8pYzAwo5/VKH16InsHSijCK9odRrwPoZcVC04Pv0R4DL3yfDg0S0jKcO1n5u+pbtH6y4VkFfnLy13QSMxG/yB76mrxaUmAohDkqIwI/9YscZTHU09KYjo=
