language: node_js
node_js:
- '0.11'
before_install:
- gem update --system
- gem install sass
- npm install -g grunt-cli
install: npm install
before_script: grunt dist
env:
  matrix:
  - secure: DT5jubNeMm7b9ULYgU4IOMLdgfKeu3z5C84w41Yc9CkVl9tZ7VKCmOeIpZOzkLZ7vXGYuGY8KngVm8rQNw5YuyIubiOfXcRWDd0fSNJj57iq8uCuSJxrO8yQZZJKjv4lM+9XdK7NyvWn85dTm9bgnt69PvjChOLl3R7TbwpC7kA=
  - secure: Ti5/p/i1N17xpwWcDlOBUcc4VdBB0RtXBSsX2y8e5MI6csgqdxs9X38sSH5uBj5D/S6H5oNf4reolYECIt2wZe/Sq1wFfwwChqOOvIn5gQh+DaNIgIcAxbH9NammRf8tm6tHnbUudwnB4xBWhqaCIMGStIcLTOTRWDm5ZGwPpFc=
