language: node_js
node_js:
- '0.11'
before_install:
- gem update --system
- gem install sass
- npm install -g grunt-cli
install: npm install
before_script: grunt dist
env:
  global:
  - secure: "DlEBEJWqhRwADq32HRz9CwM3cg41tLZfDCnS0RHVIzM6Z/0C1UQw1IKPvzA5y1Q/twCRfRmEOBm7j2DaONd8sSsNWXpRMQgIMAWLgwRLit+3XNgINC4irzJDis+XbGDuIhIzkhcD4nmEP9Sr3QQeRfE/XVSNlv/yvIZWxUK02x8="
  - secure: "pscYO0eif/adYsCirn8bTRlfwrEFJIKy6WjYmWlKkMONitAlE3LXxL7Nxsbci6pQFDd1vWrq8LJuPUJpJJyR4D4pDeL+6uSYlywgEhlCcD8sNdpvycI1OrdoMwA3EPt8asVVu0GCQlb1br/btWE6FZBHzSQjft3DPDfijzbyZgc="
