language: node_js
node_js:
- '0.11'
before_install:
- gem update --system
- gem install sass
- npm install -g grunt-cli
install: npm install
before_script: grunt dist
env:
  global:
  - secure: Iu3jZUtfSUl5MNGQ1ymQA12RHDM9UQHt0VH2V3ie9mTJMX1LuYfemqnwrQAg/A9bk0BAGKcaXPmokGuS5D4CwJi/InCCSdearETrMk9Jo3A+/h1VNr68fZDwpR+09TxK4K6o2V79wRJlUzqbG7Z9neZzcvmE/dsNfWCU6Xy5gXk=
  - secure: bz4g3Xkx1Bu2h0uXGxuYYS9RTbJVD2RKPt+h224AIe//1mZGZJbtIrxtku3pdIsQ4ULl01attGN/Zi7I5zNeZNWpGA9Cq/Lysbd6KSzormzNwugqLpPVl2Vlp60UfeJFVka73MB+Xk/IZzbbfm8NLJNxtPSRCRBWrPEhXZJVqm0=
