language: node_js
node_js:
- '0.11'
before_install:
- gem update --system
- gem install sass
- npm install -g grunt-cli
install: npm install
before_script: grunt dist
env:
  global:
  - secure: U+QtJ9BI052XWWFbKWlFhgyOxQHvIoAT0uQ+cLCUSSAJhgxDZErLvtrgLY0vT0xgGxcVeUCmp+Ck6ICgjvYokS726bT2TgYSNAy43rJRsXPeVQBVh/Su+EkNfo37mtHzd7pdcm8I9XC+OUj0fQ/j6Zapfp00/W82f3jBkmm4Ido=
  - secure: jMVvS+EFKrdHfgm9TSNlpuc7kSznxv3eObVF2CelN3mppuDFSr5QJgHRj1m4DwipPe0Qpz1zm/BcdRU489JeKj/TW1sfLrHTXuj5VRdcrp8Lwdf4f8mHnTTwh5DOyIOFxqNs9n61gnhko5ETjpwGrkGaWu7n7a2fYKLMVjk4Jg0=
